INFO:     Will watch for changes in these directories: ['/home/calvinnigrini/Projects/ADA/backend']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [99525] using WatchFiles
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [99538]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:51246 - "POST /api/login HTTP/1.1" 200 OK
INFO:     127.0.0.1:36590 - "POST /api/login HTTP/1.1" 200 OK
INFO:     127.0.0.1:45070 - "POST /api/login HTTP/1.1" 200 OK
INFO:     127.0.0.1:45082 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:45090 - "GET /api/notifications/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:45104 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:45110 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:53590 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:44134 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:51808 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:46976 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:40308 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:56232 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:37148 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:36252 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:44164 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:32988 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:43632 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:39016 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:52548 - "GET /api/models/me HTTP/1.1" 401 Unauthorized
WARNING:  WatchFiles detected changes in 'test_rules_engine.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [99538]
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [133434]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib64/python3.13/site-packages/urllib3/contrib/emscripten/__init__.py', 'venv/lib64/python3.13/site-packages/requests/certs.py', 'venv/lib64/python3.13/site-packages/charset_normalizer/constant.py', 'venv/lib64/python3.13/site-packages/requests/__init__.py', 'venv/lib64/python3.13/site-packages/urllib3/_version.py', 'venv/lib64/python3.13/site-packages/urllib3/util/retry.py', 'venv/lib64/python3.13/site-packages/certifi/core.py', 'venv/lib64/python3.13/site-packages/charset_normalizer/models.py', 'venv/lib64/python3.13/site-packages/urllib3/http2/connection.py', 'venv/lib64/python3.13/site-packages/requests/__version__.py', 'venv/lib64/python3.13/site-packages/urllib3/contrib/emscripten/request.py', 'venv/lib64/python3.13/site-packages/charset_normalizer/utils.py', 'venv/lib64/python3.13/site-packages/charset_normalizer/cli/__init__.py', 'venv/lib64/python3.13/site-packages/urllib3/http2/__init__.py', 'venv/lib64/python3.13/site-packages/urllib3/util/ssl_match_hostname.py', 'venv/lib64/python3.13/site-packages/urllib3/util/util.py', 'venv/lib64/python3.13/site-packages/charset_normalizer/cli/__main__.py', 'venv/lib64/python3.13/site-packages/requests/packages.py', 'venv/lib64/python3.13/site-packages/requests/sessions.py', 'venv/lib64/python3.13/site-packages/requests/help.py', 'venv/lib64/python3.13/site-packages/charset_normalizer/__init__.py', 'venv/lib64/python3.13/site-packages/urllib3/filepost.py', 'venv/lib64/python3.13/site-packages/urllib3/poolmanager.py', 'venv/lib64/python3.13/site-packages/urllib3/util/wait.py', 'venv/lib64/python3.13/site-packages/requests/auth.py', 'venv/lib64/python3.13/site-packages/urllib3/contrib/pyopenssl.py', 'venv/lib64/python3.13/site-packages/urllib3/contrib/emscripten/connection.py', 'venv/lib64/python3.13/site-packages/requests/api.py', 'venv/lib64/python3.13/site-packages/charset_normalizer/version.py', 'venv/lib64/python3.13/site-packages/urllib3/util/request.py', 'venv/lib64/python3.13/site-packages/urllib3/util/ssltransport.py', 'venv/lib64/python3.13/site-packages/urllib3/util/__init__.py', 'venv/lib64/python3.13/site-packages/urllib3/util/response.py', 'venv/lib64/python3.13/site-packages/urllib3/connectionpool.py', 'venv/lib64/python3.13/site-packages/requests/hooks.py', 'venv/lib64/python3.13/site-packages/charset_normalizer/api.py', 'venv/lib64/python3.13/site-packages/urllib3/util/timeout.py', 'venv/lib64/python3.13/site-packages/urllib3/_collections.py', 'venv/lib64/python3.13/site-packages/charset_normalizer/cd.py', 'venv/lib64/python3.13/site-packages/urllib3/util/url.py', 'venv/lib64/python3.13/site-packages/requests/models.py', 'venv/lib64/python3.13/site-packages/urllib3/response.py', 'venv/lib64/python3.13/site-packages/certifi/__main__.py', 'venv/lib64/python3.13/site-packages/urllib3/contrib/emscripten/fetch.py', 'venv/lib64/python3.13/site-packages/requests/exceptions.py', 'venv/lib64/python3.13/site-packages/urllib3/http2/probe.py', 'venv/lib64/python3.13/site-packages/urllib3/util/ssl_.py', 'venv/lib64/python3.13/site-packages/urllib3/_request_methods.py', 'venv/lib64/python3.13/site-packages/urllib3/connection.py', 'venv/lib64/python3.13/site-packages/requests/status_codes.py', 'venv/lib64/python3.13/site-packages/urllib3/util/connection.py', 'venv/lib64/python3.13/site-packages/urllib3/util/proxy.py', 'venv/lib64/python3.13/site-packages/charset_normalizer/__main__.py', 'venv/lib64/python3.13/site-packages/requests/_internal_utils.py', 'venv/lib64/python3.13/site-packages/requests/structures.py', 'venv/lib64/python3.13/site-packages/urllib3/contrib/emscripten/response.py', 'venv/lib64/python3.13/site-packages/urllib3/contrib/socks.py', 'venv/lib64/python3.13/site-packages/urllib3/exceptions.py', 'venv/lib64/python3.13/site-packages/charset_normalizer/md.py', 'venv/lib64/python3.13/site-packages/requests/compat.py', 'venv/lib64/python3.13/site-packages/certifi/__init__.py', 'venv/lib64/python3.13/site-packages/urllib3/_base_connection.py', 'venv/lib64/python3.13/site-packages/requests/cookies.py', 'venv/lib64/python3.13/site-packages/requests/adapters.py', 'venv/lib64/python3.13/site-packages/charset_normalizer/legacy.py', 'venv/lib64/python3.13/site-packages/urllib3/__init__.py', 'venv/lib64/python3.13/site-packages/requests/utils.py', 'venv/lib64/python3.13/site-packages/urllib3/fields.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [133434]
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [133751]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:40874 - "POST /api/login HTTP/1.1" 422 Unprocessable Content
WARNING:  WatchFiles detected changes in 'test_rules_engine.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [133751]
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [133867]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:37576 - "POST /api/login HTTP/1.1" 200 OK
INFO:     127.0.0.1:37578 - "POST /api/rules/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:37586 - "GET /api/rules/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:37596 - "GET /api/models/me HTTP/1.1" 200 OK
WARNING:  WatchFiles detected changes in 'routes/__init__.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [133867]
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [134135]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'services/__init__.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [134135]
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [134244]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:32922 - "POST /api/login HTTP/1.1" 200 OK
INFO:     127.0.0.1:32934 - "POST /api/rules/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:32940 - "GET /api/rules/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:32950 - "GET /api/models/me HTTP/1.1" 200 OK
WARNING:  WatchFiles detected changes in 'routes/rules.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [134244]
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [134518]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:48158 - "POST /api/login HTTP/1.1" 200 OK
INFO:     127.0.0.1:48168 - "POST /api/rules/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:48184 - "GET /api/rules/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:48192 - "GET /api/models/me HTTP/1.1" 200 OK
WARNING:  WatchFiles detected changes in 'test_rules_engine.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [134518]
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [134615]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:39692 - "POST /api/login HTTP/1.1" 200 OK
INFO:     127.0.0.1:39708 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:39714 - "GET /api/notifications/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:39722 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:51994 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:39904 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:39918 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:35614 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:47376 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:53656 - "GET /api/models/me HTTP/1.1" 200 OK
WARNING:  WatchFiles detected changes in 'routes/rules.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [134615]
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [153305]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'services/rule_service.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [153305]
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [153567]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:42780 - "GET /api/rules/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:42782 - "GET /api/rules/executions HTTP/1.1" 422 Unprocessable Content
INFO:     127.0.0.1:59662 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:43938 - "GET /api/rules/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:43950 - "GET /api/rules/executions HTTP/1.1" 422 Unprocessable Content
INFO:     127.0.0.1:55430 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:42556 - "GET /api/rules/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:42564 - "GET /api/rules/executions HTTP/1.1" 422 Unprocessable Content
INFO:     127.0.0.1:49938 - "GET /api/models/me HTTP/1.1" 401 Unauthorized
INFO:     127.0.0.1:37320 - "POST /api/login HTTP/1.1" 200 OK
INFO:     127.0.0.1:37334 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:37328 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:37348 - "GET /api/notifications/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:37362 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:37370 - "GET /api/notifications/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:37366 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:37380 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:37386 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:42988 - "GET /api/models/me HTTP/1.1" 401 Unauthorized
WARNING:  WatchFiles detected changes in 'routes/rules.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [153567]
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
Process SpawnProcess-11:
Traceback (most recent call last):
  File "/usr/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/usr/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/server.py", line 78, in _serve
    config.load()
    ~~~~~~~~~~~^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/importer.py", line 22, in import_from_string
    raise exc from None
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/calvinnigrini/Projects/ADA/backend/main.py", line 3, in <module>
    from routes import models, auth, upload, jobs, generator, rules, tokens, votes, settings, notifications
  File "/home/calvinnigrini/Projects/ADA/backend/routes/rules.py", line 8, in <module>
    from models.models import Rule
ModuleNotFoundError: No module named 'models.models'
WARNING:  WatchFiles detected changes in 'routes/rules.py'. Reloading...
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
Process SpawnProcess-12:
Traceback (most recent call last):
  File "/usr/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/usr/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/server.py", line 78, in _serve
    config.load()
    ~~~~~~~~~~~^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/importer.py", line 22, in import_from_string
    raise exc from None
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/calvinnigrini/Projects/ADA/backend/main.py", line 3, in <module>
    from routes import models, auth, upload, jobs, generator, rules, tokens, votes, settings, notifications
  File "/home/calvinnigrini/Projects/ADA/backend/routes/rules.py", line 8, in <module>
    from models.models import Rule
ModuleNotFoundError: No module named 'models.models'
WARNING:  WatchFiles detected changes in 'routes/rules.py'. Reloading...
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
Process SpawnProcess-13:
Traceback (most recent call last):
  File "/usr/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/usr/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/server.py", line 78, in _serve
    config.load()
    ~~~~~~~~~~~^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/importer.py", line 22, in import_from_string
    raise exc from None
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/calvinnigrini/Projects/ADA/backend/main.py", line 3, in <module>
    from routes import models, auth, upload, jobs, generator, rules, tokens, votes, settings, notifications
  File "/home/calvinnigrini/Projects/ADA/backend/routes/rules.py", line 6, in <module>
    from models.db_models import Rule
ModuleNotFoundError: No module named 'models.db_models'
WARNING:  WatchFiles detected changes in 'routes/rules.py'. Reloading...
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [177176]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:45700 - "POST /api/login HTTP/1.1" 200 OK
INFO:     127.0.0.1:45710 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:45716 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:45712 - "GET /api/notifications/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:45722 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:45726 - "GET /api/notifications/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:45732 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:45742 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:45744 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:47532 - "GET /api/models/me HTTP/1.1" 401 Unauthorized
INFO:     127.0.0.1:49452 - "POST /api/login HTTP/1.1" 200 OK
INFO:     127.0.0.1:49458 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:49474 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:49482 - "GET /api/notifications/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:39090 - "GET /api/models/in-progress HTTP/1.1" 200 OK
INFO:     127.0.0.1:39096 - "GET /api/models/active HTTP/1.1" 200 OK
INFO:     127.0.0.1:39098 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:39112 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:39126 - "GET /api/notifications/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:39122 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:39140 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:39150 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:39236 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:38180 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:60954 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:43436 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:48880 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:42918 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:53326 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:40928 - "GET /api/rules/ HTTP/1.1" 401 Unauthorized
INFO:     127.0.0.1:40942 - "POST /api/login HTTP/1.1" 200 OK
INFO:     127.0.0.1:40964 - "GET /api/notifications/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:40954 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:40970 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:40986 - "GET /api/rules/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:41010 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:41018 - "GET /api/rules/executions HTTP/1.1" 422 Unprocessable Content
INFO:     127.0.0.1:41014 - "GET /api/notifications/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:40994 - "GET /api/models/me HTTP/1.1" 200 OK
INFO:     127.0.0.1:41020 - "GET /api/rules/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:41030 - "GET /api/rules/executions HTTP/1.1" 422 Unprocessable Content
WARNING:  WatchFiles detected changes in 'services/pattern_analyzer.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [177176]
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [225208]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'services/synthetic_data_generator.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [225208]
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [225865]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'routes/generator.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [225865]
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
Process SpawnProcess-17:
Traceback (most recent call last):
  File "/usr/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/usr/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/server.py", line 78, in _serve
    config.load()
    ~~~~~~~~~~~^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/calvinnigrini/Projects/ADA/backend/main.py", line 3, in <module>
    from routes import models, auth, upload, jobs, generator, rules, tokens, votes, settings, notifications
  File "/home/calvinnigrini/Projects/ADA/backend/routes/generator.py", line 339
    raise HTTPException(status_code=500, detail=str(e)}
                                                      ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
WARNING:  WatchFiles detected changes in 'models/job.py'. Reloading...
/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
Process SpawnProcess-18:
Traceback (most recent call last):
  File "/usr/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/usr/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/server.py", line 78, in _serve
    config.load()
    ~~~~~~~~~~~^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/calvinnigrini/Projects/ADA/backend/venv/lib/python3.13/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/calvinnigrini/Projects/ADA/backend/main.py", line 3, in <module>
    from routes import models, auth, upload, jobs, generator, rules, tokens, votes, settings, notifications
  File "/home/calvinnigrini/Projects/ADA/backend/routes/generator.py", line 339
    raise HTTPException(status_code=500, detail=str(e)}
                                                      ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
INFO:     Stopping reloader process [99525]
